# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ee9c34b35bf3c6e13ebc66523707145061dd1d1059d503b6cf1bbba2814788eb6c6e306d94c3c3a9f77b5c75d6fcf21f54147c4e5dfd1addc15f9f60875471a

test:
  secret_key_base: 9c1ba4d1ecbaf451af6c810697e8f14c1d4361bf22ad4bce7011ac5603228ca9feb74009c073a6498d9b95a53ea21b10b8e309152da1370aacf4f1c4e13167b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
